[workspace]
resolver = "2"

members = [
	"crates/anomura_driver",
	"crates/mock-macro",
	"crates/context",
	"crates/anomura_plugins",
	"crates/anomura_definitions",
	"test-suite/mocks",
	#"test_project/bar"
]

[workspace.dependencies]
#rustc_plugin = { git = "https://github.com/EldritchEli/rustc_plugin.git", version = "0.15.0-nightly-2026-10-06" }
rustc_plugin = { version = "0.15.0-nightly-2026-10-06", path = "../rustc_plugin/crates/rustc_plugin" }
