[package]
name = "mock-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1" 
context = { version = "0.1.0", path = "../context" }
mockingbird = { version = "0.1.0", path = "../mockingbird" }
serde = "1.0.228"
serde_json = "1.0.149"
#driver_test = { version = "0.1.0", path = "../driver_test" } 
