[package]
name = "foo"
version = "0.1.0"
edition = "2024"

[dependencies]
bar = { version = "0.1.0", path = "../bar" }
foobar = { version = "0.1.0", path = "../foobar" }
mock-macro = { version = "0.1.0", path = "../../crates/mock-macro" }
context = { version = "0.1.0", path = "../../crates/context" }