[package]
name = "anomura_driver"
version = "0.1.0"
edition = "2024"

[dependencies]
#mock-macro = { path = "../mock-macro" }
quote = "1"
syn = { version = "2", features = ["full", "visit-mut"] }
proc-macro2 = "1"
serde = "1.0.228"
rustc_plugin = { workspace = true }
log = "0.4.29"
mock-macro = { version = "0.1.0", path = "../mock-macro" }


[package.metadata.rust-analyzer]
rustc_private = true
